version: '3'

# Upon 'docker-compose up' builds one image from Dockerfile and starts 
# a container with interactive session.   
services:
    app:
        container_name: zorro-bot
        build: .
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - ./config/config.json:/app/config.json:ro